#:schema node_modules/wrangler/config-schema.json
name = "sub"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "a5250186ba80462fbc2885e1759bdf84" }
]

[assets]
directory = "./public"
